name: tructivity
description: A new Flutter project.

publish_to: "none"

version: 1.0.3+4

environment:
  sdk: ">=2.12.0 <=3.10.6"

dependencies:
  awesome_notifications: ^0.10.1
  calendar_view: ^1.0.4
  cupertino_icons: ^1.0.6
  date_field: ^6.0.3+1
  draw_your_image: ^0.2.0
  file_picker: ^10.2.0
  flutter:
    sdk: flutter

  flutter_colorpicker: ^1.1.0
  flutter_neat_and_clean_calendar: ^0.4.16
  flutter_painter: ^1.0.1
  flutter_quill: ^11.4.1
  flutter_secure_storage: ^9.0.0
  flutter_slider_drawer: ^3.0.2
  flutter_speed_dial: ^7.0.0
  flutter_typeahead: ^5.0.1
  font_awesome_flutter: ^10.5.0
  home_widget: ^0.8.0
  local_auth: ^2.3.0
  open_file: ^3.3.2
  passcode_screen: ^2.0.0
  path_provider: ^2.1.1
  percent_indicator: ^4.0.0
  provider: ^6.0.0
  quick_actions: ^1.0.6
  screenshot: ^3.0.0
  shared_preferences: ^2.2.1
  sqflite: ^2.3.0
  syncfusion_flutter_calendar: ^30.1.39
  timetable_view: ^0.3.0
  url_launcher: ^6.1.14
  flutter_slider_drawer_v: ^2.0.2
  flutter_quill_extensions: ^11.0.0
dependency_overrides:
  intl: 0.19.0
dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_native_splash: ^2.2.19
  flutter_test:
    sdk: flutter
flutter_native_splash:
  color: "#ffffff"
  color_dark: "#1a1a1a"
  image: "images/icon-small.png"
  android: true
  ios: true
flutter:
  uses-material-design: true
  assets:
    - images/icon.png
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Black.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-ExtraBold.ttf
        - asset: fonts/Poppins-ExtraLight.ttf
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-Thin.ttf
