// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmgWe389ZPrq1sOzFAC8WAGK7O9CScl-4',
    appId: '1:728679104997:web:41687f3a66e60008b82f0c',
    messagingSenderId: '728679104997',
    projectId: 'tructivity',
    authDomain: 'tructivity.firebaseapp.com',
    storageBucket: 'tructivity.firebasestorage.app',
    measurementId: 'G-K2142CTWWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8-9Icaifr4TsHFKp_uPLBYGf5J8OFTTQ',
    appId: '1:728679104997:android:e81760e1acf57370b82f0c',
    messagingSenderId: '728679104997',
    projectId: 'tructivity',
    storageBucket: 'tructivity.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8zDLbG2L0PYMRKpoTlTGoEcNBwkjO5jg',
    appId: '1:728679104997:ios:4dbacfd93a846b79b82f0c',
    messagingSenderId: '728679104997',
    projectId: 'tructivity',
    storageBucket: 'tructivity.firebasestorage.app',
    iosBundleId: 'com.example.calenderapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8zDLbG2L0PYMRKpoTlTGoEcNBwkjO5jg',
    appId: '1:728679104997:ios:99ced42e180115a9b82f0c',
    messagingSenderId: '728679104997',
    projectId: 'tructivity',
    storageBucket: 'tructivity.firebasestorage.app',
    iosBundleId: 'com.tructivity.tructivity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmgWe389ZPrq1sOzFAC8WAGK7O9CScl-4',
    appId: '1:728679104997:web:5849b97ea054096cb82f0c',
    messagingSenderId: '728679104997',
    projectId: 'tructivity',
    authDomain: 'tructivity.firebaseapp.com',
    storageBucket: 'tructivity.firebasestorage.app',
    measurementId: 'G-CK7CN9DJQG',
  );
}
